spring.application.name=arriendo-service
server.port=${PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-db:3306/bicicleta_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bicicleta_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bicicleta_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tolerancia de espera para que Hikari no se caiga rápido
spring.datasource.hikari.initialization-fail-timeout=60000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Comunicación con el microservicio de clientes
api.cliente.url=${API_CLIENTE_URL:http://clientes-service:8081/api/v1/clientes}

# Configuración de Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html