server:
  port: ${PORT:8084}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: clientes-service
          uri: ${CLIENTES_SERVICE_URL:http://clientes-service:8081}
          predicates:
            - Path=/api/v1/clientes/**

        - id: arriendos-service
          uri: ${ARRIENDOS_SERVICE_URL:http://arriendos-service:8082}
          predicates:
            - Path=/api/v1/arriendos/**

        - id: tipos-bicicletas-service
          uri: ${ARRIENDOS_SERVICE_URL:http://arriendos-service:8082}
          predicates:
            - Path=/api/v1/tipos-bicicletas/**